# Generated by Django 5.2.3 on 2025-06-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(help_text='List of recipient email addresses')),
                ('cc', models.JSONField(blank=True, help_text='List of CC email addresses', null=True)),
                ('bcc', models.JSONField(blank=True, help_text='List of BCC email addresses', null=True)),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('raw_content', models.TextField(help_text='Raw .eml content')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ingestion.emailthread')),
            ],
        ),
    ]
