# Generated by Django 5.2.3 on 2025-06-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('rules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Aggregated compliance score', max_digits=5)),
                ('strengths', models.TextField(help_text='Summary of passed rules and best practices')),
                ('improvements', models.TextField(help_text='Summary of failed rules and suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='users.contact')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='ingestion.emailthread')),
            ],
        ),
        migrations.CreateModel(
            name='RuleOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('score', models.IntegerField(help_text='Points awarded for this rule evaluation')),
                ('justification', models.TextField()),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.emailmessage')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_outcomes', to='reports.auditreport')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
            ],
            options={
                'unique_together': {('report', 'rule', 'email_message')},
            },
        ),
    ]
