# Generated by Django 5.2.3 on 2025-06-15 17:50

from django.db import migrations


def add_dummy_email_rules(apps, schema_editor):
    Rule = apps.get_model('rules', 'Rule')
    
    dummy_rules = [
        {
            'name': 'Professionalism',
            'description': 'Evaluates the professional tone and language used in the email',
            'severity': 2,  # Medium
            'definition': {'rule': 'Evaluates the professional tone and language used in the email'},
            'is_active': True,
        },
        {
            'name': 'Grammar',
            'description': 'Checks for grammatical errors and proper sentence structure',
            'severity': 1,  # Low
            'definition': {'rule': 'Checks for grammatical errors and proper sentence structure'},
            'is_active': True,
        },
        {
            'name': 'Clarity',
            'description': 'Assesses the clarity and coherence of the email content',
            'severity': 2,  # Medium
            'definition': {'rule': 'Assesses the clarity and coherence of the email content'},
            'is_active': True,
        },
        {
            'name': 'Greeting',
            'description': 'Verifies appropriate greeting and closing in professional emails',
            'severity': 1,  # Low
            'definition': {'rule': 'Verifies appropriate greeting and closing in professional emails'},
            'is_active': True,
        },
        {
            'name': 'Explicit Content',
            'description': 'Detects inappropriate or explicit content in email communications',
            'severity': 3,  # High
            'definition': {'rule': 'Detects inappropriate or explicit content in email communications'},
            'is_active': True,
        },
    ]
    
    for rule_data in dummy_rules:
        Rule.objects.create(**rule_data)


def remove_dummy_email_rules(apps, schema_editor):
    Rule = apps.get_model('rules', 'Rule')
    rule_names = ['Professionalism', 'Grammar', 'Clarity', 'Greeting', 'Explicit Content']
    Rule.objects.filter(name__in=rule_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_dummy_email_rules, remove_dummy_email_rules),
    ]
